## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc1..aaaaaaaanz24m3dufjdmdgvhpzn2hrl2k7lgf5tvkldqpktlr2wuyqbk3m5q"
  is_repository_created_on_first_push = "true"
}

