## This configuration was generated by terraform-provider-oci

resource oci_core_nat_gateway export_nat_lab01 {
  block_traffic  = "false"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:18.445Z"
  }
  display_name = "nat_lab01"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.sa-saopaulo-1.aaaaaaaa5u34tq4jo3al3pczwshxyhocrbyr2ty3drcef2cpwpfeqlriojva"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_lab01.id
}

resource oci_core_internet_gateway export_ig_lab01 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:18.552Z"
  }
  display_name = "ig_lab01"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_lab01.id
}

resource oci_core_subnet export_subnet_pub_lab01 {
  availability_domain = var.availability_domain--DpbK-SA-SAOPAULO-1-AD-1
  cidr_block          = "172.16.1.0/24"
  compartment_id      = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:18.700Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcn_lab01.default_dhcp_options_id
  display_name    = "subnet_pub_lab01"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcn_lab01.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn_lab01.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn_lab01.id
}

resource oci_core_subnet export_subnet_prv_lab01 {
  availability_domain = var.availability_domain--DpbK-SA-SAOPAULO-1-AD-1
  cidr_block          = "172.16.2.0/24"
  compartment_id      = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:18.689Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcn_lab01.default_dhcp_options_id
  display_name    = "subnet_prv_lab01"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_vcn.export_vcn_lab01.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn_lab01.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn_lab01.id
}

resource oci_core_vcn export_vcn_lab01 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "172.16.0.0/16",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:17.512Z"
  }
  display_name = "vcn_lab01"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn_lab01 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:17.512Z"
  }
  display_name     = "Default DHCP Options for vcn_lab01"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_lab01.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn_lab01 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:17.512Z"
  }
  display_name = "Default Route Table for vcn_lab01"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_lab01.default_route_table_id
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn_lab01 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/fernando.almeida@service.com.br"
    "Oracle-Tags.CreatedOn" = "2023-10-13T12:28:17.512Z"
  }
  display_name = "Default Security List for vcn_lab01"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "172.16.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_lab01.default_security_list_id
}

